Adds plotutil example image width/height unit
gonum/plot pull request #756
Opened 2023-01-09 22:34 UTC by zyluo

Please take a look.

2023-01-10 10:19 UTC, sbinet submitted a review, later dismissed
LGTM

2023-01-10 10:31 UTC, kortschak requested changes
@sbinet Do you know why the test expectations are no longer matching?

2023-01-10 10:31 UTC, kortschak commented on plotutil/main.go
> +	if err := mkplot().Save(4*vg.Inch, 4*vg.Inch, name+".eps"); err != nil {
Since these are being changed, `10*vg.Centimeter`.

2023-01-10 15:41 UTC, zyluo commented on plotutil/main.go
> +	if err := mkplot().Save(4*vg.Inch, 4*vg.Inch, name+".eps"); err != nil {
done

2023-01-14 09:08 UTC, sbinet submitted a review, later dismissed
LGTM

(could you please add yourself to the `AUTHORS` and/or `CONTRIBUTORS` files of `gonum/gonum` ? thanks)

2023-01-14 09:11 UTC, sbinet commented
@kortschak ah, I didn't notice.
I guess another change in the X/wayland stack that ripples on `vg/vggio`...

2023-01-22 22:27 UTC, zyluo commented
I guess this patch is gated by vggio?

2023-01-22 23:10 UTC, kortschak commented
If you rebase this onto master, it should pass.

2023-02-11 21:48 UTC, zyluo commented
rebased to master

2023-02-12 00:36 UTC, kortschak approved these changes
Thanks

2023-02-12 00:38 UTC, merged